const PROSPECTS_BASE = {
  "Dark Kitchen": [
    // --- LOTE ORIGINAL ---
    { nome: "ATW Delivery Brands", contato: "atwdeliverybrands.com.br", instagram: "@atwdeliverybrands", tipo: "Holding de dark kitchens", oportunidade: "Maior holding do mundo. Operam 3 marcas em cada cozinha.", sinal: "Buscando franqueados", abrangencia: "Nacional", dor: "Cruzamento do fluxo de motoboys com o lixo e reposição de estoque", abordagem: "Desenhar layouts que impedem a contaminação cruzada e aprovam rápido" },
    { nome: "Grupo HSH (Home Sushi)", contato: "homesushihome.com.br", instagram: "@homesushihome", tipo: "Rede de dark kitchens", oportunidade: "Meta de 15 novas franquias. Alta padronização exigida.", sinal: "Expansão agressiva", abrangencia: "Nacional", dor: "Dificuldade de replicar eficiência operacional em imóveis de formatos variados", abordagem: "Oferecer projeto modular base que se adapta fácil a qualquer locação" },
    { nome: "China in Box / Gendai", contato: "chinainbox.com.br", instagram: "@chinainboxbrasil", tipo: "Grupo multimarcas", oportunidade: "Foco na expansão de unidades apenas para delivery (Dark).", sinal: "Expansão contínua", abrangencia: "Nacional", dor: "Gestão do altíssimo volume de óleo e fritura em espaços menores", abordagem: "Especialização em caixas de gordura de alta performance e filtragem" },
    { nome: "KitchenCentral", contato: "kitchencentral.com.br", instagram: "@kitchencentral", tipo: "Hub de cozinhas compartilhadas", oportunidade: "Complexos enormes alugados para dezenas de operações simultâneas.", sinal: "Novas capitais", abrangencia: "SP / RJ / BH", dor: "Superaquecimento estrutural e subdimensionamento da exaustão central", abordagem: "Compatibilização rigorosa de sistemas pesados de AVAC" },
    { nome: "Mimic", contato: "mimic.com.br", instagram: "@mimicbrasil", tipo: "Hub para marcas digitais", oportunidade: "Parceira de marcas gigantes. Fluxo e volume intensos.", sinal: "Crescimento em SP", abrangencia: "SP", dor: "Cozinhas operando no limite absoluto de pessoas e equipamentos", abordagem: "Foco em ergonomia operacional para cortar segundos vitais na montagem" },
    { nome: "Local Kitchens RJ", contato: "", instagram: "", tipo: "Galpões adaptados", oportunidade: "Grandes espaços focados em polo de delivery na Zona Sul e Tijuca.", sinal: "Alta rotatividade", abrangencia: "RJ", dor: "Readequação constante de pontos elétricos e de gás a cada novo inquilino", abordagem: "Desenho de infraestrutura 'plug and play' flexível para rodízio de operadores" },
    { nome: "Smart Kitchens", contato: "smartkitchens.com.br", instagram: "@smartkitchens", tipo: "Cozinhas modulares", oportunidade: "Módulos de 15m² a 30m² otimizados para iFood.", sinal: "Novos polos", abrangencia: "SP / RJ", dor: "Aproveitamento milimétrico do espaço sem perder área fria de estocagem", abordagem: "Layout em formato 'Tetris' unindo a engenharia do cardápio à arquitetura" },
    
    // --- LOTE 1 ---
    { nome: "Oli Pizzas", contato: "olipizzas.com.br", instagram: "@olipizzas", tipo: "Delivery Premium", oportunidade: "Forte atuação no mercado digital de pizzas em São Paulo.", sinal: "Alta demanda", abrangencia: "SP", dor: "Altas temperaturas dos fornos de pizza em galpões de delivery fechados", abordagem: "Exaustão localizada e isolamento térmico de fornos para saúde ocupacional da equipe" },
    { nome: "Apptite", contato: "apptite.com", instagram: "@apptite", tipo: "Hub de Chefs", oportunidade: "Plataforma que integra cozinhas independentes para delivery artesanal.", sinal: "Novas praças", abrangencia: "SP", dor: "Flexibilidade espacial para abrigar diferentes tipos de gastronomia na mesma planta", abordagem: "Criação de baias modulares com pontos de elétrica e gás flexíveis" },

    // --- LOTE 2 ---
    { nome: "Kitchen Mate", contato: "kitchenmate.com.br", instagram: "@kitchenmatebr", tipo: "Dark Kitchen Modular", oportunidade: "Galpões logísticos convertidos em dezenas de boxes operacionais.", sinal: "Expansão em SP", abrangencia: "SP", dor: "Subdimensionamento da rede elétrica e de exaustão central quando todos os boxes operam no pico", abordagem: "Projeto de infraestrutura descentralizada e gestão de carga térmica" },
    { nome: "Hub Food Service", contato: "hubfood.com.br", instagram: "@hubfoodservice", tipo: "Hub de Delivery", oportunidade: "Foco em áreas nobres com alto adensamento.", sinal: "Novos polos", abrangencia: "RJ / SP", dor: "Adaptação de exaustão em galpões antigos no Centro do Rio e SP sem afetar vizinhança", abordagem: "Sistemas de lavagem de gases e isolamento acústico de maquinário pesado" },
    { nome: "Delivery Center", contato: "deliverycenter.com", instagram: "@deliverycenter", tipo: "Cozinha Integrada a Shoppings", oportunidade: "Utilização de áreas mortas de shoppings e estacionamentos.", sinal: "Parcerias com Malls", abrangencia: "Nacional", dor: "Aprovação travada pela engenharia do shopping devido a rotas de fuga e extração", abordagem: "Modelagem executiva em BIM focada em aprovação rápida e compatibilização de dutos" },
    { nome: "Eat Local", contato: "eatlocal.com.br", instagram: "@eatlocal_br", tipo: "Galpão Compartilhado", oportunidade: "Modelo de locação flexível para marcas menores entrarem no delivery.", sinal: "Crescimento orgânico", abrangencia: "PR / SC", dor: "Cruzamento do fluxo de lixo orgânico com a entrada de insumos limpos", abordagem: "Desenho de fluxograma rigoroso com docas setorializadas e barreiras sanitárias" },
    { nome: "Ghost Kitchens BR", contato: "ghostkitchens.com.br", instagram: "@ghostkitchensbr", tipo: "Rede de Franquias Ghost", oportunidade: "Franqueamento do modelo de negócio invisível.", sinal: "Captação de franqueados", abrangencia: "SP", dor: "Padronização de plantas para franqueados em imóveis completamente irregulares", abordagem: "Criação de módulos arquitetônicos adaptáveis (plug and play)" },
    { nome: "Web Kitchens", contato: "webkitchens.com.br", instagram: "@webkitchens", tipo: "Locação de Boxes", oportunidade: "Alta rotatividade de locatários e adaptações constantes.", sinal: "Ampliação de unidades", abrangencia: "RJ", dor: "Pisos industriais e ralos cedendo rapidamente com a troca de operadores", abordagem: "Especificação de revestimentos uretânicos de alta espessura e grelhas industriais" },
    { nome: "Foodtech Hub", contato: "foodtechhub.com.br", instagram: "@foodtechhub", tipo: "Incubadora de Marcas", oportunidade: "Testes de conceito que viram operações fixas.", sinal: "Lojas de teste", abrangencia: "SP", dor: "Necessidade de alterar o layout da cozinha quente a cada nova marca residente", abordagem: "Conexões de gás e elétrica via engates rápidos e ilhas móveis" },
    { nome: "Cloud Foods", contato: "cloudfoods.com.br", instagram: "@cloudfoods_oficial", tipo: "Operadora de Delivery", oportunidade: "Gerenciamento de 5 a 10 marcas virtuais na mesma planta.", sinal: "Aumento de portfólio", abrangencia: "PR", dor: "Caos na expedição de pedidos com motoboys de diferentes plataformas", abordagem: "Layout de expedição com triagem eletrônica e docas de retirada blindadas" },
    { nome: "Virtual Kitchen CO", contato: "virtualkitchen.com.br", instagram: "@virtualkitchenco", tipo: "Cozinhas Híbridas", oportunidade: "Delivery que permite take-away com pequena vitrine frontal.", sinal: "Novo formato", abrangencia: "SC / RS", dor: "Odor forte de fritura escapando para a área de take-away e rua", abordagem: "Pressurização positiva da área de atendimento e cortinas de ar dimensionadas" },
    { nome: "Cozinha de Bairro", contato: "cozinhadebairro.com", instagram: "@cozinhadebairro", tipo: "Micro Dark Kitchen", oportunidade: "Imóveis de 20m² a 30m² em bairros residenciais.", sinal: "Descentralização", abrangencia: "RJ / SP", dor: "Falta de área fria (câmaras) exigindo fretes diários e encarecendo a operação", abordagem: "Otimização volumétrica para empilhamento de estocagem refrigerada" },
    { nome: "GastroHub SP", contato: "gastrohub.com.br", instagram: "@gastrohubsp", tipo: "Hub de Cozinhas", oportunidade: "Galpões na Zona Sul de SP.", sinal: "Crescimento de módulos", abrangencia: "SP", dor: "Dificuldade na compartimentação de incêndio entre os boxes operacionais", abordagem: "Modelagem BIM para rotas de fuga e extração centralizada" },
    { nome: "Carioca Cloud Kitchens", contato: "cariocacloud.com.br", instagram: "@cariocacloud", tipo: "Dark Kitchen Compartilhada", oportunidade: "Expansão na Zona Norte do RJ.", sinal: "Novos galpões", abrangencia: "RJ", dor: "Gargalo na central de resíduos com o calor gerando odores rápidos", abordagem: "Projeto de câmara de lixo refrigerada e doca isolada" },
    { nome: "Uai Food Spaces", contato: "uaifood.com.br", instagram: "@uaifoodspaces", tipo: "Locação de Cozinhas", oportunidade: "Dominância na região central de BH.", sinal: "Novas praças", abrangencia: "MG", dor: "Adequação de imóveis residenciais antigos para carga elétrica industrial", abordagem: "Retrofit de entrada de energia e quadros de carga setorizados" },
    { nome: "Vitória Delivery Center", contato: "vitoriadecenter.com.br", instagram: "@vixdelivery", tipo: "Hub Logístico Food", oportunidade: "Maior polo focado em delivery do ES.", sinal: "Alta ocupação", abrangencia: "ES", dor: "Problemas de umidade e maresia corroendo equipamentos externos de exaustão", abordagem: "Especificação de exaustores em aço inox 316 e pintura epóxi marítima" },
    { nome: "Berrini Foodtech", contato: "berrinifoodtech.com.br", instagram: "@berrinifood", tipo: "Hub Premium", oportunidade: "Foco em marcas de alto padrão.", sinal: "Alta rotatividade", abrangencia: "SP", dor: "Odor de cocção pesada invadindo os andares corporativos superiores", abordagem: "Sistema de filtragem de duplo estágio com carvão ativado e ozônio" },
    { nome: "Rio Delivery Hub", contato: "riodeliveryhub.com", instagram: "@riodeliveryhub", tipo: "Espaços Modulares", oportunidade: "Retrofit de áreas no Centro do RJ.", sinal: "Revitalização", abrangencia: "RJ", dor: "Restrições de fachada em prédios históricos impedindo dutos visíveis", abordagem: "Exaustão com lavadores de gases compactos internamente alocados" },
    { nome: "Savassi Ghost", contato: "savassighost.com.br", instagram: "@savassighost", tipo: "Cozinha Invisível", oportunidade: "Atendimento de alta demanda noturna.", sinal: "Expansão de turnos", abrangencia: "MG", dor: "Acústica da operação noturna gerando multas na vizinhança residencial", abordagem: "Isolamento acústico de forros e amortecedores de vibração em motores" },
    { nome: "Campinas Cloud", contato: "campinascloud.com.br", instagram: "@campinascloud", tipo: "Hub Interior SP", oportunidade: "Expansão forte no interior paulista.", sinal: "Novos complexos", abrangencia: "SP", dor: "Cruzamento do fluxo de insumos com a expedição de motoboys", abordagem: "Layout em fluxo unidirecional (marcha avante) sem cruzamentos" },
    { nome: "Niterói Kitchens", contato: "niteroikitchens.com.br", instagram: "@niteroikitchens", tipo: "Hub Regional", oportunidade: "Atendendo massivamente a região oceânica.", sinal: "Demanda aquecida", abrangencia: "RJ", dor: "Falta de área de apoio para higienização de caixas de delivery", abordagem: "Criação de central de higienização de caixas com drenagem de alta vazão" },
    { nome: "Mooca Food Labs", contato: "moocafoodlabs.com.br", instagram: "@moocafoodlabs", tipo: "Incubadora de Delivery", oportunidade: "Módulos de teste rápido para empreendedores.", sinal: "Turnover de marcas", abrangencia: "SP", dor: "Pisos danificados rapidamente por arraste de equipamentos pesados", abordagem: "Aplicação de poliuretano cimentício de 6mm com rodapés abaulados" }
  ],
  "Hamburgueria": [
    // --- LOTE ORIGINAL ---
    { nome: "La Brasa Burger", contato: "labrasaburger.com.br", instagram: "@labrasaburger", tipo: "Artesanal", oportunidade: "140 unidades com operações pesadas. Meta de 20 novas lojas.", sinal: "Expansão ativa", abrangencia: "Nacional", dor: "Fumaça e gordura pesada das chapas invadindo a área de clientes", abordagem: "Diagnóstico e readequação potente do sistema de exaustão" },
    { nome: "Cabana Burger", contato: "cabanaburger.com.br", instagram: "@cabanaburger", tipo: "Premium", oportunidade: "Unidades padrão de 120m² que exigem projeto técnico completo.", sinal: "Entrada em novos estados", abrangencia: "SP / RJ / MG", dor: "Manter o alto padrão estético alinhado a uma cozinha de guerra hiper produtiva", abordagem: "Conexão perfeita entre o design de interiores e a retaguarda invisível" },
    { nome: "Johnny Rockets", contato: "johnnyrockets.com.br", instagram: "@johnnyrocketsbrasil", tipo: "Temática", oportunidade: "Segunda maior operação do mundo. Obras exigentes em shoppings.", sinal: "Crescimento franchising", abrangencia: "Nacional", dor: "Limitações rigorosas de shoppings para aprovação de coifas e ar-condicionado", abordagem: "Especialização nos trâmites e aprovações junto à engenharia de shoppings" },
    { nome: "T.T. Burger", contato: "ttburger.com.br", instagram: "@t.t.burger", tipo: "Premium (Grupo Trigo)", oportunidade: "Marca carioca com forte expansão em SP e shoppings do RJ.", sinal: "Novas lojas", abrangencia: "RJ / SP", dor: "Adaptar a estética industrial bruta aos guias de loja fechados dos shoppings", abordagem: "Harmonização de materiais industriais aprováveis pelas fiscalizações" },
    { nome: "Patties", contato: "patties.com.br", instagram: "@pattiesburger", tipo: "Ultra-smash burger", oportunidade: "Fenômeno de fluxo. Lojas super compactas focadas em volume extremo.", sinal: "Expansão acelerada", abrangencia: "SP", dor: "Linha de montagem e fluxo de motoboys congestionando espaços minúsculos", abordagem: "Otimização milimétrica de bancadas para produção em formato de esteira contínua" },
    { nome: "B de Burger", contato: "bdeburger.com", instagram: "@bdeburger", tipo: "Na brasa", oportunidade: "Rede carioca focada em grelhas parilla. Orçamentos robustos.", sinal: "Retrofit e expansão", abrangencia: "RJ", dor: "Calor extremo irradiado pelas grelhas afetando a produtividade da equipe", abordagem: "Soluções de conforto térmico e sistemas de compensação de ar inteligente" },
    { nome: "Z Deli Sandwiches", contato: "zdeli.com.br", instagram: "@zdelisandwiches", tipo: "Premiada", oportunidade: "Operação no limite da capacidade. Necessidade de salões e apoios extras.", sinal: "Abertura de apoios", abrangencia: "SP", dor: "Falta de área física para gerir o alto volume de insumos frescos diários", abordagem: "Criação de centros de preparação isolados (commissary kitchens) muito eficientes" },

    // --- LOTE 1 ---
    { nome: "Bullguer", contato: "bullguer.com", instagram: "@bullguer", tipo: "Smash Burger / Fast Casual", oportunidade: "Pioneiros no smash no Brasil, com expansão contínua e lojas de rua de alto fluxo.", sinal: "Expansão Sudeste", abrangencia: "SP / RJ / MG", dor: "Cozinhas compactas lidando com alto volume de fumaça gerada pela técnica de smash na chapa quente", abordagem: "Sistemas de exaustão de alta vazão com compensação de ar para evitar pressão negativa no salão" },
    { nome: "Jeronimo Burger", contato: "jeronimoburger.com.br", instagram: "@jeronimoburger", tipo: "Fast Food Premium (Grupo Madero)", oportunidade: "Lojas focadas em autoatendimento e extrema velocidade operacional.", sinal: "Lojas modulares", abrangencia: "Nacional", dor: "Integração do fluxo de totens digitais com a esteira de montagem sem gargalos na entrega", abordagem: "Layout em linha de produção linear para otimização de tempo e movimento da equipe" },
    { nome: "O Burguês", contato: "oburgues.com", instagram: "@oburgues", tipo: "Delivery e Lojas Físicas", oportunidade: "Forte atuação no modelo de dark kitchen e take away no Rio de Janeiro, expandindo para SP.", sinal: "Dominância regional", abrangencia: "RJ / SP", dor: "Conflito físico entre motoboys esperando pedidos e o fluxo de operação da loja", abordagem: "Desenho de janelas de expedição isoladas e áreas de espera com conforto térmico para entregadores" },
    { nome: "Bucaneiro", contato: "bucaneiroburger.com.br", instagram: "@bucaneiroburger", tipo: "Artesanal", oportunidade: "Crescimento sólido nos bairros do Rio de Janeiro com lojas de perfil rústico e industrial.", sinal: "Abertura de unidades", abrangencia: "RJ", dor: "Adequação de imóveis antigos de rua para suportar carga elétrica e extração de ar", abordagem: "Retrofit de infraestrutura pesada preservando a estética industrial da marca" },

    // --- LOTE 2 ---
    { nome: "Sheesh!", contato: "sheesh.com.br", instagram: "@sheeshburger", tipo: "Smash e Ultra-Smash", oportunidade: "Operação extremamente visual, muito forte no interior de SP.", sinal: "Lojas de rua", abrangencia: "SP", dor: "Fila de espera invadindo calçadas e dificultando o fluxo do salão", abordagem: "Integração do design de interiores com áreas de descompressão fluídas" },
    { nome: "Holy Burger", contato: "holyburger.com.br", instagram: "@holyburgersp", tipo: "Artesanal Premium", oportunidade: "Referência no Centro de SP. Operação madura buscando otimização.", sinal: "Reforma / Ampliação", abrangencia: "SP", dor: "Cozinha quente compacta operando além do limite de conforto térmico", abordagem: "Retrofit de ventilação mecânica com insuflamento de ar tratado na praça quente" },
    { nome: "Baggio Burger", contato: "baggioburger.com.br", instagram: "@baggioburger", tipo: "Franquia Regional", oportunidade: "Forte penetração em Santa Catarina e Paraná.", sinal: "Captação agressiva", abrangencia: "SC / PR", dor: "Dificuldade em replicar a mesma identidade visual em fachadas muito distintas", abordagem: "Manualização arquitetônica executiva para garantir o padrão visual da marca" },
    { nome: "Seven Kings", contato: "sevenkingsburger.com.br", instagram: "@sevenkingsburger", tipo: "Temática Premium", oportunidade: "Lojas que são verdadeiros cenários. Projetos de alto valor agregado.", sinal: "Novas praças", abrangencia: "SP", dor: "Harmonizar decoração imersiva pesada com as exigências da vigilância sanitária", abordagem: "Detalhamento de marcenaria e iluminação que camuflam a infraestrutura técnica" },
    { nome: "Severo Burger", contato: "severoburger.com.br", instagram: "@severoburger", tipo: "Artesanal de Rua", oportunidade: "Unidades com perfil descolado no Sul, migrando para Sudeste.", sinal: "Expansão Sudeste", abrangencia: "RS / SP", dor: "Equilíbrio acústico em salões com estilo industrial e muita superfície rígida", abordagem: "Tratamento de ruído com nuvens acústicas e painéis disfarçados no design" },
    { nome: "Burger Joint", contato: "burgerjoint.com.br", instagram: "@burgerjointbr", tipo: "Submundo / Descolada", oportunidade: "Estética 'rabiscada' proposital, mas que exige infraestrutura invisível perfeita.", sinal: "Retrofit e Manutenção", abrangencia: "RJ / SP", dor: "Dutos de ar e elétrica visíveis acumulando gordura em estética industrial aberta", abordagem: "Projeto executivo de eletrocalhas e dutos de fácil manutenção e limpeza diária" },
    { nome: "Oso Smash", contato: "ososmash.com.br", instagram: "@ososmash", tipo: "Fast Smash", oportunidade: "Foco absoluto em delivery e balcão ultra rápido.", sinal: "Lojas enxutas", abrangencia: "RJ", dor: "Ergonomia da chapa: operador perde segundos girando para acessar ingredientes", abordagem: "Desenho da praça de cocção em 'U' para que o chapeiro alcance tudo a um braço de distância" },
    { nome: "Z Deli", contato: "zdeli.com.br", instagram: "@zdelisandwiches", tipo: "Premiada", oportunidade: "Altíssimo volume de produção e exigência gastronômica.", sinal: "Estruturação de retaguarda", abrangencia: "SP", dor: "Falta de área física nas lojas antigas para estocagem e pré-preparo", abordagem: "Desenvolvimento de commissary kitchens (cozinhas centrais) de alta eficiência" },
    { nome: "Meats", contato: "restaurantemeats.com.br", instagram: "@meats", tipo: "Autor / Premium", oportunidade: "Foco na experiência de consumo no salão com grelhas pesadas.", sinal: "Otimização de layout", abrangencia: "SP", dor: "Calor irradiado do broiler chegando nas primeiras mesas do salão", abordagem: "Cálculo de barreiras térmicas invisíveis (cortinas de ar) entre cozinha e clientes" },
    { nome: "Cabana Burger Campinas", contato: "cabanaburger.com.br", instagram: "@cabanaburger", tipo: "Premium Casual", oportunidade: "Expansão agressiva no interior paulista.", sinal: "Lojas de rua", abrangencia: "SP", dor: "Dimensionamento de ar-condicionado em salões com pé direito duplo", abordagem: "Cálculo de carga térmica e insuflamento estratificado" },
    { nome: "TT Burger Niterói", contato: "ttburger.com.br", instagram: "@t.t.burger", tipo: "Premium Artesanal", oportunidade: "Forte entrada em shoppings fora do Rio capital.", sinal: "Novas lojas", abrangencia: "RJ", dor: "Adequação do padrão estético rústico às normas restritas de shoppings", abordagem: "Compatibilização de materiais não-combustíveis com aspecto industrial" },
    { nome: "Underdog Meat", contato: "underdogmeat.com.br", instagram: "@underdogmeat", tipo: "Parrilla e Burger", oportunidade: "Público fidelizado e volume insano em SP.", sinal: "Otimização de espaço", abrangencia: "SP", dor: "Calor irradiado das grelhas afetando a produtividade em espaço exíguo", abordagem: "Projeto de cortina de ar na boqueta e insuflamento direto no operador" },
    { nome: "Eddie Fine Burgers", contato: "eddiefine.com.br", instagram: "@eddiefineburgers", tipo: "Casual Dining", oportunidade: "Marca clássica passando por modernização.", sinal: "Retrofit de lojas", abrangencia: "MG", dor: "Cozinhas antigas com fluxos estrangulados atrasando o tempo de mesa", abordagem: "Reengenharia da praça de montagem para reduzir passos do chapeiro" },
    { nome: "Rick's Burger", contato: "ricksburger.com.br", instagram: "@ricksburger", tipo: "Artesanal Extremo", oportunidade: "Fenômeno capixaba gerando filas na porta.", sinal: "Lojas âncoras", abrangencia: "ES", dor: "Gestão do fluxo caótico de clientes aguardando pedidos de viagem dentro do salão", abordagem: "Criação de zona de transição e espera isolada da operação" },
    { nome: "Patties Pinheiros", contato: "patties.com.br", instagram: "@pattiesburger", tipo: "Ultra-Smash Rápido", oportunidade: "Volume brutal de entregas em poucos metros quadrados.", sinal: "Sempre lotado", abrangencia: "SP", dor: "Acúmulo rápido de gordura nas coifas devido ao método smash extremo", abordagem: "Especificação de coifas wash-down (autolaváveis) para operação contínua" },
    { nome: "B de Burger Barra", contato: "bdeburger.com", instagram: "@bdeburger", tipo: "Na Brasa Premium", oportunidade: "Consolidação na Zona Oeste carioca.", sinal: "Público alto padrão", abrangencia: "RJ", dor: "Interferência do ruído da exaustão pesada no conforto acústico da varanda", abordagem: "Atenuadores de ruído na rede de dutos e caixas plenum" },
    { nome: "Frank & Charles", contato: "frankcharles.com.br", instagram: "@frankcharles", tipo: "Artesanal Comfort", oportunidade: "Operação enxuta e super detalhista.", sinal: "Manutenção", abrangencia: "SP", dor: "Falta de área fria para descanso de blends de carne in loco", abordagem: "Integração de gaveteiros refrigerados sob a chapa (chef bases)" },
    { nome: "Jeca Burger", contato: "jecaburger.com.br", instagram: "@jecaburger", tipo: "Temático", oportunidade: "Potência em franquias no interior de MG.", sinal: "Novas franquias", abrangencia: "MG", dor: "Padronização do balcão de atendimento em layouts de imóveis diferentes", abordagem: "Desenho paramétrico de mobiliário para fácil adaptação de medidas" },
    { nome: "Buzin Burger", contato: "buzinburger.com.br", instagram: "@buzinburger", tipo: "Rodízio de Mini Burgers", oportunidade: "Modelo de alto giro exigindo maquinário pesado.", sinal: "Abertura de salões", abrangencia: "RJ", dor: "Volume extremo de fritadeiras exigindo renovação de óleo constante", abordagem: "Sistema de tubulação e tanque para descarte e abastecimento de óleo central" }
  ],
  "Café": [
    // --- LOTE ORIGINAL ---
    { nome: "Cheirin Bão", contato: "cheirinbao.com.br", instagram: "@cheirinbao", tipo: "Café especial", oportunidade: "Mais de 900 unidades. Maior rede de cafeterias do país.", sinal: "Sempre captando", abrangencia: "Nacional", dor: "Padronização visual e de fluxo em pontos comerciais de tamanhos muito variados", abordagem: "Desenvolvimento de manualização arquitetônica para padronizar franqueados" },
    { nome: "Sterna Café", contato: "sternacafe.com.br", instagram: "@sternacafe", tipo: "Premium", oportunidade: "Meta de 40 novas unidades. Foco em lojas instagramáveis.", sinal: "Contratos assinados", abrangencia: "Nacional", dor: "O salão é lindo, mas a retaguarda e área de lavagem ficam caóticas e visíveis", abordagem: "Projetar o 'coração escondido' que garante a beleza e a limpeza contínua" },
    { nome: "Casa Bauducco", contato: "casabauducco.com.br", instagram: "@casabauducco", tipo: "Cafeteria + empório", oportunidade: "Dois formatos vitais: quiosque menor e loja completa.", sinal: "Expansão contínua", abrangencia: "Nacional", dor: "Exposição de produtos secos concorrendo com o espaço das estufas quentes", abordagem: "Marcenaria inteligente voltada 100% para o vitrinismo e venda por impulso" },
    { nome: "The Slow Bakery", contato: "theslowbakery.com.br", instagram: "@theslowbakery", tipo: "Padaria e café", oportunidade: "Mistura fábrica de pães com salão. Altíssimo nível de exigência técnica.", sinal: "Filiais-satélite", abrangencia: "RJ", dor: "Controle térmico sensível da fermentação natural colidindo com o calor dos fornos", abordagem: "Especialização em conforto térmico e desenho de vitrines técnicas refrigeradas" },
    { nome: "We Coffee", contato: "wecoffee.com.br", instagram: "@wecoffee.br", tipo: "Instagramável", oportunidade: "Lojas que são obras de arquitetura futurista. Investimentos imensos.", sinal: "Expansão viral", abrangencia: "SP", dor: "Gestão do fluxo brutal de filas sem destruir a experiência acústica do salão", abordagem: "Integração de tratamento acústico premium com fluxo limpo de clientes" },
    { nome: "Curto Café", contato: "curtocafe.com.br", instagram: "@curtocafe", tipo: "Torrefação", oportunidade: "Modelo de negócio no Centro do RJ com ilhas de serviço independentes.", sinal: "Expansão orgânica", abrangencia: "RJ", dor: "Layout aberto onde o cliente interage com os equipamentos livremente (risco)", abordagem: "Desenho de fluxos intuitivos e proteção sutil do maquinário de torra" },
    { nome: "Coffee Lab", contato: "coffeelab.com.br", instagram: "@coffeelab_br", tipo: "Laboratório de torra", oportunidade: "O maquinário de torra faz parte da experiência visual de interiores.", sinal: "Sempre em obras", abrangencia: "SP", dor: "Extração de gases da torra do café sem afetar o cheiro agradável do ambiente", abordagem: "Engenharia sutil de micro-exaustão para áreas sensíveis" },

    // --- LOTE 1 ---
    { nome: "The Coffee", contato: "thecoffee.jp", instagram: "@thecoffee.jp", tipo: "To Go / Minimalista", oportunidade: "Lojas ultracompactas (algumas com menos de 10m²). Padrão estético rigoroso.", sinal: "Expansão Nacional", abrangencia: "PR / SP / Nacional", dor: "Encaixar toda a marcenaria, maquinário, hidráulica e estoque em espaços mínimos", abordagem: "Compatibilização milimétrica em BIM para marcenaria técnica e ergonomia em microespaços" },
    { nome: "Mais1 Café", contato: "mais1cafe.com.br", instagram: "@mais1cafe", tipo: "Franquia To Go", oportunidade: "Uma das redes que mais cresce no modelo pegue e leve, ideal para quiosques e pequenas lojas.", sinal: "Centenas de lojas", abrangencia: "Nacional", dor: "Rápida aprovação de projetos padronizados em diferentes prefeituras e shoppings", abordagem: "Elaboração de cadernos executivos padrão e gestão ágil de aprovações legais" },
    { nome: "Go Coffee", contato: "gocoffee.com.br", instagram: "@gocoffeebrasil", tipo: "Cafeteria Grab and Go", oportunidade: "Forte presença em Curitiba e espalhando pelo Sul/Sudeste. Variedade de snacks e bebidas.", sinal: "Expansão orgânica", abrangencia: "PR / SC / SP", dor: "Concorrência de espaço visual entre os equipamentos de café e a vitrine de doces", abordagem: "Desenho de balcões vitrine iluminados que não bloqueiam a interação com o barista" },
    { nome: "Dark Coffee", contato: "darkcoffeebr.com", instagram: "@darkcoffeerio", tipo: "Cafeteria Contemporânea", oportunidade: "Lojas amplas, focadas em coworking e permanência no Centro e Zona Sul carioca.", sinal: "Novas lojas conceito", abrangencia: "RJ", dor: "Gestão acústica em grandes salões com piso duro e muitas pessoas trabalhando", abordagem: "Especificação de forros e revestimentos acústicos disfarçados na decoração estética" },

    // --- LOTE 2 ---
    { nome: "Um Coffee Co.", contato: "umcoffeeco.com.br", instagram: "@umcoffeeco", tipo: "Café Especial e Torra", oportunidade: "Do campo à xícara. Lojas sofisticadas no Itaim e Pinheiros.", sinal: "Expansão premium", abrangencia: "SP", dor: "Integração de equipamentos de torra no meio do salão sem gerar fumaça ou ruído excessivo", abordagem: "Engenharia de exaustão cenográfica e micro-isolamento acústico em vidro" },
    { nome: "Bastarda", contato: "bastarda.com.br", instagram: "@bastardacafe", tipo: "Café e Ciclismo", oportunidade: "Conceito híbrido fortíssimo na Zona Sul carioca.", sinal: "Público nichado", abrangencia: "RJ", dor: "Fluxo de bicicletas dentro da loja conflitando com o serviço de mesas", abordagem: "Layout multifuncional com parkings internos que servem de expositor" },
    { nome: "Supernova Coffee", contato: "supernovacoffee.com.br", instagram: "@supernovacoffee", tipo: "Café Especial e Roasters", oportunidade: "Potência em Curitiba. Design industrial e foco extremo no grão.", sinal: "Abertura de unidades", abrangencia: "PR", dor: "Aproveitamento de imóveis tombados ou antigos, com restrições de reforma estrutural", abordagem: "Projetos de arquitetura efêmera e instalações aparentes que respeitam o patrimônio" },
    { nome: "Pato Rei", contato: "patoreisp.com.br", instagram: "@patoreisp", tipo: "Café e Gastronomia Asiática", oportunidade: "Operação complexa que mistura cafeteria fina com cozinha quente pesada.", sinal: "Expansão de conceito", abrangencia: "SP", dor: "Exaustão da cozinha asiática concorrendo com o aroma delicado do café no salão", abordagem: "Separação rigorosa de pressões de ar (negativa na cozinha, positiva no café)" },
    { nome: "Bollocks", contato: "bollocks.com.br", instagram: "@bollockscafe", tipo: "Café Estilo Rock/Industrial", oportunidade: "Visual carregado, música e café especial.", sinal: "Retrofit", abrangencia: "SC / PR", dor: "Acústica do ambiente sobrecarregada, tornando a conversa impossível", abordagem: "Aplicação de materiais fonoabsorventes escondidos na decoração rústica" },
    { nome: "Por um Punhado de Dólares", contato: "porumpunhado.com.br", instagram: "@porumpunhadodedolares", tipo: "Café Urbano de Rua", oportunidade: "Alto fluxo no balcão, estilo caótico controlado no centro de SP.", sinal: "Fluxo intenso", abrangencia: "SP", dor: "Balcão estreito de atendimento travando a agilidade dos baristas em horário de pico", abordagem: "Reengenharia do balcão de serviço focado na velocidade de extração do espresso" },
    { nome: "Takkø Café", contato: "takkocafe.com", instagram: "@takkocafe", tipo: "Minimalista Asiático", oportunidade: "Estética limpa, operação focada e menu restrito.", sinal: "Público fidelizado", abrangencia: "SP", dor: "Ocultar 100% da bagunça de serviço (lavagem de louça) em um design minimalista aberto", abordagem: "Desenho de 'paredes cegas' e fluxos de descarte completamente invisíveis ao cliente" },
    { nome: "Botanica Casa", contato: "botanicacasa.com.br", instagram: "@botanica.casa", tipo: "Café e Paisagismo", oportunidade: "Integração de loja de plantas com cafeteria instagramável.", sinal: "Lojas amplas", abrangencia: "RJ", dor: "Aumento da umidade do ambiente devido às plantas afetando os equipamentos de café", abordagem: "Cálculo de climatização e desumidificação especializada para ambientes híbridos" },
    { nome: "Isso é Café", contato: "issoecafe.com.br", instagram: "@issoecafe", tipo: "Café e Mirante", oportunidade: "Foco em pontos icônicos (como o Mirante 9 de Julho).", sinal: "Ocupação de espaços públicos", abrangencia: "SP", dor: "Adaptação de infraestrutura técnica pesada em espaços públicos e históricos", abordagem: "Gestão executiva de projetos com aprovações em órgãos de patrimônio (Condephaat, etc)" },
    { nome: "Tato Café", contato: "tatocafe.com", instagram: "@tatocafe", tipo: "Café de Bairro", oportunidade: "Foco em experiência intimista e artesanal.", sinal: "Retrofit", abrangencia: "SP", dor: "Máquinas de espresso grandes criando barreira visual entre barista e cliente", abordagem: "Rebaixamento da bancada técnica e uso de módulos sob o balcão" },
    { nome: "Curto Café Centro", contato: "curtocafe.com.br", instagram: "@curtocafe", tipo: "Modelo de Confiança", oportunidade: "Operação massiva no Centro do Rio.", sinal: "Expansão de conceito", abrangencia: "RJ", dor: "Logística de reposição de grãos no meio do fluxo de milhares de clientes", abordagem: "Acessos ocultos e armazenamento verticalizado na retaguarda" },
    { nome: "Oop Café", contato: "oopcafe.com.br", instagram: "@oop.cafe", tipo: "Especial e Torra", oportunidade: "Referência estética e de qualidade em BH.", sinal: "Alta exigência", abrangencia: "MG", dor: "Climatização da área de torra sem interferir na estabilidade da extração", abordagem: "Isolamento técnico e exaustão dedicada para a torradora" },
    { nome: "Kaffa Cafeteria", contato: "kaffacafe.com.br", instagram: "@kaffacafe", tipo: "Premium ES", oportunidade: "Pioneiros em especialidade em Vitória.", sinal: "Consolidação", abrangencia: "ES", dor: "Vitrines de doces ressecando os produtos com o passar das horas", abordagem: "Especificação de vitrines com controle de umidade passiva e frio estático" },
    { nome: "FUTURO Refeitório", contato: "futurorefeitorio.com.br", instagram: "@futurorefeitorio", tipo: "Padaria e Café", oportunidade: "Galpão industrial convertido de altíssimo fluxo.", sinal: "Sempre cheio", abrangencia: "SP", dor: "Acústica terrível em galpões de teto alto com liquidificadores operando", abordagem: "Tratamento acústico de teto com celulose projetada e baffles suspensos" },
    { nome: "Slow Bakery Botafogo", contato: "theslowbakery.com.br", instagram: "@theslowbakery", tipo: "Fermentação Natural", oportunidade: "Volume industrial com cara de artesanal no RJ.", sinal: "Nova fábrica", abrangencia: "RJ", dor: "Câmaras de fermentação tomando muito espaço cego do salão", abordagem: "Desenho de câmaras de vidro vitrine, integrando a fermentação ao visual" },
    { nome: "Pão de Queijaria", contato: "apaodequeijaria.com.br", instagram: "@apaodequeijaria", tipo: "Café Regional", oportunidade: "Rede focada no produto mineiro em formato boutique.", sinal: "Lojas compactas", abrangencia: "MG", dor: "Múltiplos fornos de convecção gerando calor excessivo na área de balcão", abordagem: "Exaustão pontual capilarizada sobre a bateria de fornos" },
    { nome: "Urbe Café Bar", contato: "urbecafe.com.br", instagram: "@urbecafebar", tipo: "Café e Drinks", oportunidade: "Operação de longo horário na rua Augusta.", sinal: "Movimento contínuo", abrangencia: "SP", dor: "Transição de iluminação e funcionalidade do bar do dia para a noite", abordagem: "Projeto luminotécnico dinâmico e estações de trabalho flexíveis" },
    { nome: "Sofá Café", contato: "sofacafe.com.br", instagram: "@sofacafe", tipo: "Coworking", oportunidade: "Ambientes desenhados para longa permanência.", sinal: "Novas franquias", abrangencia: "SP", dor: "Necessidade de dezenas de pontos elétricos sem poluir o visual do salão", abordagem: "Instalação de piso elevado ou eletrocalhas estéticas sob as mesas" },
    { nome: "Zuka Café", contato: "zukacafe.com.br", instagram: "@zukacafe", tipo: "Café em Shopping", oportunidade: "Operação refinada e integrada a livrarias/shoppings.", sinal: "Parcerias fortes", abrangencia: "RJ", dor: "Limitações hídricas (falta de ponto de esgoto) em áreas secas do shopping", abordagem: "Uso de bombas de recalque compactas embutidas na marcenaria" }
  ],
  "Restaurante À la Carte": [
    // --- LOTE ORIGINAL ---
    { nome: "Divino Fogão", contato: "divinofogao.com.br", instagram: "@divinofogao", tipo: "Culinária brasileira", oportunidade: "Novo conceito de megaloja de 600m² exigindo revisão arquitetônica.", sinal: "Novo conceito", abrangencia: "Nacional", dor: "Sistemas de banho-maria desperdiçando muita energia elétrica e hídrica", abordagem: "Eficiência energética através de especificação técnica sustentável" },
    { nome: "Espetto Carioca", contato: "espettocarioca.com.br", instagram: "@espettocarioca", tipo: "Bar e restaurante", oportunidade: "Modelo híbrido físico + dark kitchen. Forte presença.", sinal: "Expansão interior", abrangencia: "Nacional", dor: "Integração do bar, salão de alto fluxo e saída intensa de pedidos via motoboy", abordagem: "Separação arquitetônica clara entre as rotas de garçons e entregadores" },
    { nome: "Gurumê", contato: "japagurume.com.br", instagram: "@gurume_oficial", tipo: "Japonês contemporâneo", oportunidade: "Projetos arquitetônicos premiados. Orçamentos milionários.", sinal: "Expansão contínua", abrangencia: "RJ / SP", dor: "Garantir a funcionalidade suja da cozinha quente sob acabamentos de altíssimo luxo", abordagem: "Atuar como Parceiro Técnico especializado desenhando a retaguarda invisível" },
    { nome: "Ráscal", contato: "rascal.com.br", instagram: "@rascalrestaurante", tipo: "Cozinha mediterrânea", oportunidade: "Restaurantes imensos com ilhas de preparo à vista do cliente.", sinal: "Renovando lojas", abrangencia: "SP / RJ", dor: "Exaustão complexa de grandes ilhas centrais sem bloquear a visão do salão", abordagem: "Soluções avançadas de coifas arquitetônicas de alto padrão sem ruído" },
    { nome: "Grupo Irajá", contato: "grupoiraja.com.br", instagram: "@grupoiraja", tipo: "Multimarcas", oportunidade: "Grupo gastronômico renomado lançando novos conceitos anualmente.", sinal: "Novas marcas", abrangencia: "RJ", dor: "Velocidade na virada de chave de obra para inaugurar num imóvel existente", abordagem: "Gerenciamento ágil de projetos executivos focados em retrofit de rápida execução" },
    { nome: "Famiglia Mancini", contato: "famigliamancini.com.br", instagram: "@famigliamancini", tipo: "Cantinas italianas", oportunidade: "Operações gigantescas na mesma rua que requerem manutenção.", sinal: "Expansão local", abrangencia: "SP", dor: "Cozinhas muito antigas que precisam de modernização sem parar o restaurante", abordagem: "Projetos de intervenção cirúrgica e modernização faseada de retaguarda" },

    // --- LOTE 1 ---
    { nome: "Madero Steak House", contato: "restaurantemadero.com.br", instagram: "@maderobrasil", tipo: "Casual Dining", oportunidade: "Operações parrudas em shoppings e rodovias. Cozinhas industriais completas.", sinal: "Potência do Sul", abrangencia: "Nacional", dor: "Logística interna complexa (recebimento de congelados da fábrica vs. produção local)", abordagem: "Dimensionamento correto de câmaras frias e setorização suja/limpa rigorosa" },
    { nome: "Tragga", contato: "tragga.com.br", instagram: "@restaurantetragga", tipo: "Carnes Premium", oportunidade: "Carnes na brasa e culinária sofisticada no Rio de Janeiro. Ambientes de alto padrão.", sinal: "Consolidação na Zona Sul", abrangencia: "RJ", dor: "Carga térmica severa da parrilla impactando o rendimento do chef e da equipe", abordagem: "Projeto de ventilação mecânica com insuflamento de ar fresco focado na praça quente" },
    { nome: "Mocotó", contato: "mocoto.com.br", instagram: "@mocotorestaurante", tipo: "Cozinha Sertaneja", oportunidade: "Lojas em shoppings e expansão do conceito a partir da matriz na Zona Norte de SP.", sinal: "Novos modelos", abrangencia: "SP", dor: "Equipamentos de grande litragem (panelões) que danificam o piso e dificultam a limpeza", abordagem: "Especificação de pisos resinados de alta espessura e ralos lineares industriais" },
    { nome: "Paris 6", contato: "paris6.com.br", instagram: "@paris6", tipo: "Bistrô 24h", oportunidade: "Operação que não para. Obras e manutenções precisam ser cirúrgicas.", sinal: "Modelo de franquia Petit", abrangencia: "Nacional", dor: "Desgaste acelerado de revestimentos e infraestrutura devido à operação ininterrupta", abordagem: "Utilização de materiais de ultra durabilidade e acesso facilitado para manutenção sem quebrar paredes" },

    // --- LOTE 2 ---
    { nome: "Nino Cucina", contato: "ninocucina.com.br", instagram: "@ninocucina", tipo: "Italiano Casual Premium", oportunidade: "Parte do grupo Famiglia Nino, expansão acelerada pelo Brasil.", sinal: "Expansão Nacional", abrangencia: "SP / RJ", dor: "Cozinhas originais subdimensionadas para o sucesso absoluto e filas do restaurante", abordagem: "Retrofit brutal de áreas de apoio e criação de praças de massas de alta densidade" },
    { nome: "Oteque", contato: "oteque.com", instagram: "@oteque_rj", tipo: "Alta Gastronomia (Estrela Michelin)", oportunidade: "Referência absoluta em Botafogo, RJ. Nível máximo de exigência técnica.", sinal: "Otimização milimétrica", abrangencia: "RJ", dor: "Controle absoluto de ruído e temperatura na cozinha aberta, que é o palco do restaurante", abordagem: "Sistemas de exaustão silenciosos e iluminação técnica de precisão hospitalar" },
    { nome: "Cora", contato: "cora.sp.com", instagram: "@cora.sp", tipo: "Contemporâneo / Rooftop", oportunidade: "Localizado no topo de prédio no Centro de SP. Logística complexa.", sinal: "Alta demanda", abrangencia: "SP", dor: "Abastecimento e retirada de lixo por elevadores limitados em prédio antigo", abordagem: "Gerenciamento de obra e fluxo logístico reverso planejado na planta baixa" },
    { nome: "Oro", contato: "ororestaurante.com.br", instagram: "@oro_restaurante", tipo: "Alta Gastronomia / Parrilla", oportunidade: "Cozinha focada na brasa (Felipe Bronze).", sinal: "Manutenção de alto nível", abrangencia: "RJ", dor: "Risco de incêndio e fuligem severa nos dutos de parrilla em ambiente de luxo", abordagem: "Projeto de segurança contra incêndio e filtros umidificadores para parrillas" },
    { nome: "A Baianeira", contato: "abaianeira.com.br", instagram: "@abaianeira", tipo: "Comida Brasileira de Autor", oportunidade: "Lojas icônicas (MASP e Barra Funda).", sinal: "Crescimento em polos culturais", abrangencia: "SP", dor: "Operar cozinhas robustas dentro de instituições culturais com regras estritas (Museus)", abordagem: "Trâmites de aprovação complexos e infraestrutura 100% não-destrutiva" },
    { nome: "Irajá Redux", contato: "grupoiraja.com.br", instagram: "@irajaredux", tipo: "Contemporâneo Casual", oportunidade: "Uma das marcas do Grupo Irajá, adaptável a shoppings.", sinal: "Expansão Zona Sul/Barra", abrangencia: "RJ", dor: "Padronização do serviço e entrega em layouts comerciais irregulares e apertados", abordagem: "Projeto modular das estações de cocção para fácil replicação" },
    { nome: "Aizomê", contato: "aizome.com.br", instagram: "@aizomerestaurante", tipo: "Japonês Tradicional", oportunidade: "Lojas focadas em técnica pura (Japan House, etc).", sinal: "Retrofit de instalações", abrangencia: "SP", dor: "Controle rigoroso de temperatura na área de manipulação de pescados vs. conforto do salão", abordagem: "Câmaras frigoríficas de vidro e praças de sushiman com climatização direcionada" },
    { nome: "Fazenda Churrascada", contato: "fazendachurrascada.com.br", instagram: "@fazendachurrascada", tipo: "Mega Operação de Fogo", oportunidade: "Espaços gigantescos focados em fogo de chão, defumação e parrilla.", sinal: "Público massivo", abrangencia: "SP / PR", dor: "Dimensionamento monumental de fluxo de carnes cruas e gestão de toneladas de lenha", abordagem: "Layout de escala industrial disfarçado em arquitetura rústica e fluída" },
    { nome: "Lasai", contato: "lasai.com.br", instagram: "@restaurantelasai", tipo: "Farm to Table", oportunidade: "Imóvel histórico no RJ, operação focada no ingrediente.", sinal: "Renovação técnica", abrangencia: "RJ", dor: "Estrutura do casarão antigo não suporta vibração de grandes motores de ar", abordagem: "Especificação de compressores remotos e AVAC de baixo impacto estrutural" },
    { nome: "Arturito", contato: "arturito.com.br", instagram: "@restaurantearturito", tipo: "Cozinha de Fogo Clássica", oportunidade: "Restaurante consolidado de Paola Carosella. Foco na operação sustentável.", sinal: "Manutenção e Retrofit", abrangencia: "SP", dor: "Eficiência energética e hídrica em uma cozinha com fornos pesados", abordagem: "Retrofit sustentável com reaproveitamento de calor e otimização de lavagem" },
    { nome: "A Figueira Rubaiyat", contato: "gruporubaiyat.com", instagram: "@rubaiyatbrasil", tipo: "Carnes Premium", oportunidade: "Salões gigantes e alta gastronomia tradicional.", sinal: "Otimização", abrangencia: "SP", dor: "Operação de cocção pesada que precisa ser invisível para um salão refinado", abordagem: "Desenho de fluxos de serviço completamente blindados e portas acústicas" },
    { nome: "Aprazível", contato: "aprazivel.com.br", instagram: "@aprazivel", tipo: "Culinária Brasileira", oportunidade: "Imóvel escalonado nas ladeiras de Santa Teresa.", sinal: "Logística dura", abrangencia: "RJ", dor: "Movimentação de insumos e lixo por escadarias e níveis íngremes do terreno", abordagem: "Instalação de monta-cargas camuflados na arquitetura e câmaras em níveis estratégicos" },
    { nome: "Glouton", contato: "glouton.com.br", instagram: "@gloutonbh", tipo: "Autoral (Leo Paixão)", oportunidade: "Alta gastronomia premiada com exigência máxima.", sinal: "Manutenção", abrangencia: "MG", dor: "Ergonomia do Chef no passe de montagem dos pratos (gargalo de tempo)", abordagem: "Estação de passe customizada com aquecimento infravermelho e resfriamento inferior" },
    { nome: "Papaguth", contato: "papaguth.com.br", instagram: "@papaguth", tipo: "Frutos do Mar", oportunidade: "Restaurante tradicional atendendo turismo e executivos.", sinal: "Referência no ES", abrangencia: "ES", dor: "Isolamento da área de evisceração de peixes para evitar contaminação cruzada e odores", abordagem: "Sala de preparo de pescados climatizada a 15ºC com ozonizador de ambiente" },
    { nome: "Fasano Restaurante", contato: "fasano.com.br", instagram: "@fasano", tipo: "Italiano Clássico", oportunidade: "Padrão de luxo absoluto e constante renovação técnica.", sinal: "Retrofits noturnos", abrangencia: "SP", dor: "Renovação dos sistemas de lavagem sem paralisar o hotel/restaurante", abordagem: "Planejamento executivo de obra e substituição de maquinário por módulos plugáveis" },
    { nome: "Lilia", contato: "liliarestaurante.com", instagram: "@lilia.restaurante", tipo: "Contemporâneo / Centro", oportunidade: "Imóvel tombado antigo com operação cultuada.", sinal: "Adequação estrutural", abrangencia: "RJ", dor: "Infiltrações e restrições de peso nas lajes de pavimentos de madeira antigos", abordagem: "Reforço estrutural leve e impermeabilização emborrachada de poliuretano" },
    { nome: "Pacato", contato: "pacatobh.com.br", instagram: "@pacatobh", tipo: "Cozinha de Quintal", oportunidade: "Conceito que une alta gastronomia ao fogo caipira.", sinal: "Restaurante em alta", abrangencia: "MG", dor: "Fornos a lenha exigindo grande volume de armazenamento de madeira dentro do layout", abordagem: "Design de nichos de armazenamento corta-fogo integrados à decoração do salão" },
    { nome: "Corrutela", contato: "corrutela.com.br", instagram: "@corrutela", tipo: "Sustentável e Zero Waste", oportunidade: "Moinho e composteira operando no salão.", sinal: "Visão ecológica", abrangencia: "SP", dor: "Integração do maquinário de compostagem (que gera calor e gás) sem afetar o cliente", abordagem: "Câmara de compostagem isolada termicamente com extração de ar dedicada" },
    { nome: "Clan BBQ", contato: "clanbbq.com.br", instagram: "@clanbbq", tipo: "Carnes e Fogo", oportunidade: "Forte impacto térmico operando em bairro de alto padrão.", sinal: "Novas unidades", abrangencia: "RJ", dor: "Controle rigoroso da fumaça de lenha em ruas estritamente residenciais", abordagem: "Filtros precipitadores eletrostáticos e lavadores de gases pesados de alta eficiência" },
    { nome: "Tuju", contato: "tuju.com.br", instagram: "@tuju_sp", tipo: "Duas Estrelas Michelin", oportunidade: "Cozinha dividida por etapas sensoriais.", sinal: "Complexidade extrema", abrangencia: "SP", dor: "Setorização de confeitaria e cozinha quente operando perfeitamente e simultaneamente", abordagem: "Layout em zonas climáticas independentes (18ºC para doces, 24ºC para quentes)" }
  ],
  "Buffet Self-Service": [
    // --- LOTE ORIGINAL ---
    { nome: "Churras Express", contato: "churrasexpress.com.br", instagram: "@churrasexpress", tipo: "Grelhados", oportunidade: "Múltiplos formatos: loja, quiosque, container. Muito adaptável.", sinal: "Alta demanda", abrangencia: "Nacional", dor: "Necessidade de aprovar exaustão de grelhados em formatos compactos como containers", abordagem: "Soluções de filtragem eletrostática para fumaça em espaços onde não há duto externo" },
    { nome: "Brasileirinho", contato: "brasileirinho.com.br", instagram: "@brasileirinho", tipo: "Delivery e buffet", oportunidade: "Cozinha com produção de altíssima escala exige projeto detalhado.", sinal: "Novos pontos", abrangencia: "Nacional", dor: "Dimensionamento incorreto das panelas industriais e fogões gerando perda de calor", abordagem: "Consultoria técnica no correto dimensionamento térmico e fluxo de lavagem pesada" },
    { nome: "Frontera", contato: "frontera.com.br", instagram: "@fronterarestaurante", tipo: "Buffet internacional", oportunidade: "Amplos salões e ilhas temáticas complexas de cocção ao vivo.", sinal: "Retrofit de lojas", abrangencia: "RJ", dor: "Fluxo cruzado constante entre reposição pesada da equipe e fila de clientes", abordagem: "Layout estratégico com vias de serviço ocultas e ilhas frontais independentes" },
    { nome: "Manihi Sushi", contato: "manihisushi.com.br", instagram: "@manihisushi", tipo: "Rodízio premium", oportunidade: "Rodízios de alto padrão com grandes balcões frios integrados.", sinal: "Alta competição", abrangencia: "SP", dor: "Vazão da cozinha quente atrasando o ritmo agressivo dos pedidos via tablet na mesa", abordagem: "Redesenho completo das praças quentes e área de expedição exclusiva para o salão" },
    { nome: "A Mineira", contato: "amineira.com.br", instagram: "@restauranteamineira", tipo: "Comida regional", oportunidade: "Unidades gigantes no RJ. Estilo rústico com cozinhas super pesadas.", sinal: "Otimização", abrangencia: "RJ", dor: "Manutenção cara de pisos e drenagem destruídos por panelões e alta temperatura", abordagem: "Especificação exata de pisos de ultra-resistência, ralos sifonados e canaletas" },

    // --- LOTE 1 ---
    { nome: "Mania de Churrasco", contato: "maniadechurrasco.com.br", instagram: "@maniadechurrascoprime", tipo: "Fast Casual / Churrasco", oportunidade: "Presença maciça nas praças de alimentação. Equipamentos pesados à vista do cliente.", sinal: "Líder em shoppings", abrangencia: "SP / RJ / Nacional", dor: "Restrições rigorosíssimas da engenharia de shoppings para coifas de churrasqueiras", abordagem: "Sistemas de lavadores de gases e precipitadores eletrostáticos para liberação de alvará" },
    { nome: "Spoleto", contato: "spoleto.com.br", instagram: "@spoleto_oficial", tipo: "Culinária Italiana Rápida", oportunidade: "Gigante carioca que está passando por retrofit do projeto arquitetônico (Minha Cozinha Italiana).", sinal: "Retrofit de rede", abrangencia: "Nacional", dor: "Otimização da vitrine de ingredientes refrigerada que sofre com o calor da praça de massas", abordagem: "Desenho de ilhas de cocção frontal com barreira térmica invisível para proteger os frios" },

    // --- LOTE 2 ---
    { nome: "Viena", contato: "viena.com.br", instagram: "@vienarestaurante", tipo: "Buffet em Shoppings", oportunidade: "Rede tradicional passando por modernização visual e operacional.", sinal: "Retrofit de rede", abrangencia: "SP / RJ", dor: "Layout linear antigo gerando filas enormes nos caixas durante o pico", abordagem: "Reestruturação para modelo de 'ilhas de comida' (scramble system) para diluir filas" },
    { nome: "Couve Flor", contato: "couveflor.com.br", instagram: "@couveflorrestaurante", tipo: "Buffet Premium", oportunidade: "Tradicional no Jardim Botânico, alto fluxo no almoço.", sinal: "Referência na Zona Sul", abrangencia: "RJ", dor: "Bandejas frias condensando e pingando água no mobiliário do buffet", abordagem: "Detalhamento de marcenaria técnica com drenagem embutida para pistas frias" },
    { nome: "Apfel Restaurante Vegetariano", contato: "apfel.com.br", instagram: "@apfelrestaurante", tipo: "Buffet Orgânico", oportunidade: "Forte atuação no Centro de SP, foco em sustentabilidade.", sinal: "Público nichado", abrangencia: "SP", dor: "Operar com foco em lixo zero e compostagem dentro de imóveis antigos e apertados", abordagem: "Desenho de praça de processamento de orgânicos integrada à rotina de lavagem" },
    { nome: "Portucho", contato: "portucho.com.br", instagram: "@portucho_oficial", tipo: "Buffet com Grelhados", oportunidade: "Operação mista (self-service de saladas + carnes na mesa).", sinal: "Expansão de franquias", abrangencia: "SP", dor: "Dificuldade de cruzar o fluxo de garçons com espetos e clientes com pratos nas mãos", abordagem: "Circulação setorizada e alargamento de corredores críticos (chokepoints)" },
    { nome: "Delírio Tropical", contato: "deliriotropical.com.br", instagram: "@deliriotropical", tipo: "Buffet Saudável de Balcão", oportunidade: "Modelo híbrido carioca de enorme sucesso e altíssima velocidade.", sinal: "Otimização contínua", abrangencia: "RJ", dor: "Gargalo na velocidade dos atendentes servindo através do balcão de vidro", abordagem: "Estudo ergonômico da profundidade das cubas para minimizar fadiga da equipe" },
    { nome: "Avenida Paulista Pizzeria (Almoço)", contato: "avenidapaulistapizzeria.com.br", instagram: "@avenidapaulistapizzeria", tipo: "Buffet Executivo", oportunidade: "Pizzarias que rodam buffet pesado e requintado no horário do almoço.", sinal: "Operação Híbrida", abrangencia: "PR", dor: "Transformação do ambiente (iluminação/mesas) do buffet de dia para pizzaria à noite", abordagem: "Projeto de iluminação automatizada e mobiliário flexível para virada de turno" },
    { nome: "Manequim", contato: "manequim.com", instagram: "@manequimrestaurante", tipo: "Comida a Quilo", oportunidade: "Alta rotatividade em centros comerciais.", sinal: "Lojas de passagem", abrangencia: "SP", dor: "Pisos manchados e escorregadios ao redor das pistas de salada e azeite", abordagem: "Especificação de soleiras de contenção e revestimentos de coeficiente de atrito seguro" },
    { nome: "Camponesa", contato: "camponesa.com.br", instagram: "@restaurantecamponesa", tipo: "Buffet Caipira", oportunidade: "Restaurantes imensos de beira de estrada e interior.", sinal: "Volume de finais de semana", abrangencia: "SP", dor: "Vulnerabilidade a picos de energia e necessidade de refrigeração bruta para estocagem semanal", abordagem: "Projeto de painéis elétricos com geradores redundantes e câmara fria de alta eficiência" },
    { nome: "Pipo", contato: "piporestaurante.com", instagram: "@piporestaurante", tipo: "Buffet Sofisticado (Felipe Bronze)", oportunidade: "Buffet de autor, design impecável e ingredientes delicados.", sinal: "Público classe A", abrangencia: "RJ", dor: "Manter a comida quente impecável sem usar banhos-marias de visual industrial", abordagem: "Uso de pistas aquecidas de vidro vitrocerâmico ocultas no mármore do buffet" },
    { nome: "Galeto Mamma Mia", contato: "galetomammamia.com.br", instagram: "@galetomammamia", tipo: "Rodízio / Buffet", oportunidade: "Força bruta na Serra Gaúcha, descendo para Shoppings do Sul e SP.", sinal: "Expansão rápida", abrangencia: "RS / SC / SP", dor: "Vazão da brasa: assar e despachar frangos em massa sem travar a reposição de massas", abordagem: "Layout em formato 'T' separando a produção de fogo da expedição de guarnições quentes" },
    { nome: "Ráscal Leblon", contato: "rascal.com.br", instagram: "@rascalrestaurante", tipo: "Mediterrâneo", oportunidade: "Ilhas show-cooking muito ativas dentro de shoppings.", sinal: "Atualização de layout", abrangencia: "RJ", dor: "Exaustão das ilhas de massas no meio do salão sem poluir visualmente a estética", abordagem: "Coifas de vidro de perfil baixo com extração periférica silenciosa" },
    { nome: "Bovinu's", contato: "bovinus.com.br", instagram: "@bovinus_oficial", tipo: "Carnes e Buffet", oportunidade: "Volume brutal no horário de almoço no Centro.", sinal: "Operação intensa", abrangencia: "SP", dor: "Pistas com desgaste acelerado e deficiência na manutenção da cadeia quente", abordagem: "Retrofit das ilhas com resistências de silicone coladas sob o granito" },
    { nome: "Dona Lucinha", contato: "donalucinha.com.br", instagram: "@donalucinha", tipo: "Tradição Mineira", oportunidade: "Buffet robusto servido em panelas de pedra/barro originais.", sinal: "Manutenção de conceito", abrangencia: "MG", dor: "Panelas de pedra perdem calor rapidamente se a base não for desenhada milimetricamente", abordagem: "Adaptação de rechauds elétricos secos customizados para o formato exato das panelas" },
    { nome: "Papagalli", contato: "papagalli.com.br", instagram: "@papagallioficial", tipo: "A Quilo Premium", oportunidade: "Restaurante de altíssimo giro voltado a escritórios.", sinal: "Otimização de rotas", abrangencia: "ES", dor: "Fluxo da fila engarrafando gravemente nas áreas de grelhados", abordagem: "Separação física da estação de carnes (ilhas independentes e dispersas) para fluidez" },
    { nome: "Tradição Mineira", contato: "tradicaomineira.com.br", instagram: "@tradicaomineira", tipo: "Buffet Gigante", oportunidade: "Lojas massivas com dezenas de metros de pista quente.", sinal: "Redução de custos", abrangencia: "SP", dor: "Gasto energético absurdo gerado pela evaporação de banhos-marias antigos", abordagem: "Troca sistêmica por tecnologia de aquecimento por contato a seco (dry heat)" },
    { nome: "Restaurante Cervantes", contato: "cervantes.com.br", instagram: "@cervantesrio", tipo: "Pratos Feitos e Balcão", oportunidade: "O balcão contínuo mais famoso do Rio de Janeiro.", sinal: "Eficiência de maquinário", abrangencia: "RJ", dor: "Área de fritura grudada ao balcão precisando de ventilação sem roubar o ar gelado do salão", abordagem: "Sistemas de coifa de dupla câmara com compensação de ar externo injetado" },
    { nome: "Restaurante Fazendinha", contato: "fazendinha.com.br", instagram: "@fazendinha", tipo: "Buffet Rural", oportunidade: "Grandes espaços em chácaras e rodovias no interior.", sinal: "Volume de finais de semana", abrangencia: "SP", dor: "Dificuldade de reposição quando a pista do buffet fica muito distante do fogão", abordagem: "Implementação de baterias de pass-throughs aquecidos camuflados logo atrás das ilhas" },
    { nome: "Xico da Silva", contato: "xicodasilva.com.br", instagram: "@xicodasilvabh", tipo: "Buffet e Carnes", oportunidade: "Almoço executivo de alto padrão na capital.", sinal: "Revisão sanitária", abrangencia: "MG", dor: "Mobiliário pesado dificultando limpezas profundas exigidas pela Vigilância", abordagem: "Desenho de ilhas tubulares em aço inox suspensas ou rodiziadas para fácil lavagem" },
    { nome: "Salada Paulistana", contato: "saladapaulistana.com.br", instagram: "@saladapaulistana", tipo: "Buffet Saudável", oportunidade: "Foco exclusivo em dezenas de montagens de saladas.", sinal: "Otimização visual", abrangencia: "SP", dor: "Pistas frias com protetores salivares (sneezeguards) antiquados bloqueando a luz", abordagem: "Desenho de protetores de vidro extra-clear sem ferragens frontais e LED integrado" },
    { nome: "Couve Flor Horto", contato: "couveflor.com.br", instagram: "@couveflor", tipo: "Referência em Saladas", oportunidade: "Buffet clássico em região extremamente úmida (perto da mata).", sinal: "Manutenção", abrangencia: "RJ", dor: "Acúmulo crônico de gelo nas pistas frias em virtude da alta umidade do ar ambiente", abordagem: "Uso de serpentinas superdimensionadas atreladas a ciclos de degelo automático" }
  ]
};
