// Arquivo: base.js

const PROSPECTS_BASE = {
  "Dark Kitchen": [
    { nome: "ATW Delivery Brands", tipo: "Holding de dark kitchens — modelo 3 em 1", oportunidade: "Maior holding de dark kitchens do mundo, expansão ativa em todas as capitais. Cada unidade opera 3 marcas em uma cozinha — exige projeto técnico especializado.", sinal: "Buscando franqueados ativamente", contato: "atwdeliverybrands.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Grupo HSH (Home Sushi Home)", tipo: "Rede de dark kitchens — 3 marcas em 1 cozinha", oportunidade: "Faturou R$ 59 milhões em 2025, presente em 12 estados. Meta de 15 novas franquias em 2026. Alta padronização de cozinha exigida.", sinal: "Plano agressivo de expansão anunciado em 2026", contato: "homesushihome.com.br", instagram: "@homesushihome", abrangencia: "Nacional" },
    { nome: "China in Box / Gendai / Owan (TrendFoods)", tipo: "Grupo multimarcas — dark kitchens", oportunidade: "Opera 150+ dark kitchens das marcas do grupo. Modelo de expansão por dark kitchen é prioridade.", sinal: "Grupo em expansão contínua", contato: "chinaingbox.com.br", instagram: "@chinaingboxbrasil", abrangencia: "Nacional" },
    { nome: "KitchenCentral", tipo: "Hub de dark kitchens compartilhadas", oportunidade: "Opera em SP, RJ e BH. Cada novo hub é um projeto completo de cozinha profissional.", sinal: "Expansão para novas capitais prevista", contato: "kitchencentral.com.br", instagram: "", abrangencia: "SP, RJ, BH" },
    { nome: "L'Entrecôte de Paris (SMZTO)", tipo: "Franquia gourmet — dark kitchen", oportunidade: "Opera 33 dark kitchens com ticket médio superior ao físico. Meta de 80 dark kitchens em 3 anos.", sinal: "Meta oficial publicada — expansão em andamento", contato: "lentrecotedeparis.com.br", instagram: "", abrangencia: "SP e expansão" },
    { nome: "Mr. Fit — modelo nuvem", tipo: "Alimentação saudável — dark kitchen", oportunidade: "Investimento de R$ 25 mil por unidade. Expansão nacional, franqueados em busca de pontos.", sinal: "Modelo mais barato do mercado — alta demanda", contato: "mrfit.com.br", instagram: "@mrfit", abrangencia: "Nacional" },
    { nome: "Oli Pizzas", contato: "olipizzas.com.br", instagram: "@olipizzas", tipo: "Delivery Premium", oportunidade: "Forte atuação no mercado digital de pizzas em São Paulo.", sinal: "Alta demanda", abrangencia: "SP", dor: "Altas temperaturas dos fornos de pizza em galpões de delivery fechados", abordagem: "Exaustão localizada e isolamento térmico de fornos para saúde ocupacional da equipe" },
    { nome: "Apptite", contato: "apptite.com", instagram: "@apptite", tipo: "Hub de Chefs", oportunidade: "Plataforma que integra cozinhas independentes para delivery artesanal.", sinal: "Novas praças", abrangencia: "SP", dor: "Flexibilidade espacial para abrigar diferentes tipos de gastronomia na mesma planta", abordagem: "Criação de baias modulares com pontos de elétrica e gás flexíveis" }
  ],

  "Hamburgueria": [
    { nome: "La Brasa Burger", tipo: "Hamburgueria artesanal — modelo 4 em 1", oportunidade: "70 unidades físicas, 140 com dark kitchens. Faturou R$ 130 mi em 2024. Meta de 20 novas unidades em 2025.", sinal: "Expansão ativa em todas as regiões", contato: "labrasaburger.com.br", instagram: "@labrasaburger", abrangencia: "Nacional" },
    { nome: "Cabana Burger", tipo: "Hamburgueria premium — shoppings e ruas", oportunidade: "26 unidades, expansão para MG, PR e DF em 2025. Unidade padrão de 120m² exige projeto completo.", sinal: "Entrada em novos estados anunciada", contato: "cabana.com.br", instagram: "@cabanaburger", abrangencia: "SP, RJ, MG, PR, DF" },
    { nome: "Johnny Rockets", tipo: "Hamburgueria temática — shoppings", oportunidade: "Segunda maior operação da rede no mundo. Projetos de alto padrão exigidos em shoppings.", sinal: "Crescimento consistente no franchising", contato: "johnnyrockets.com.br", instagram: "@johnnyrockets_br", abrangencia: "Nacional" },
    { nome: "Usina Burger", tipo: "Hamburgueria artesanal — identidade industrial", oportunidade: "9 unidades em 2025, R$ 10,2 mi faturados. Expansão acelerada prevista para 2026.", sinal: "CEO declarou expansão como foco de 2026", contato: "usinaburguer.com.br", instagram: "@usinaburger", abrangencia: "Regional" },
    { nome: "N1 Chicken", tipo: "Frango frito — dark kitchen e loja física", oportunidade: "Investimento a partir de R$ 119 mil. Dois formatos de projeto: dark kitchen e loja.", sinal: "Expansão nacional em andamento", contato: "n1chicken.com.br", instagram: "@n1chicken", abrangencia: "Nacional" },
    { nome: "Bullguer", contato: "bullguer.com", instagram: "@bullguer", tipo: "Smash Burger / Fast Casual", oportunidade: "Pioneiros no smash no Brasil, com expansão contínua e lojas de rua de alto fluxo.", sinal: "Expansão Sudeste", abrangencia: "SP / RJ / MG", dor: "Cozinhas compactas lidando com alto volume de fumaça gerada pela técnica de smash na chapa quente", abordagem: "Sistemas de exaustão de alta vazão com compensação de ar para evitar pressão negativa no salão" },
    { nome: "Jeronimo Burger", contato: "jeronimoburger.com.br", instagram: "@jeronimoburger", tipo: "Fast Food Premium (Grupo Madero)", oportunidade: "Lojas focadas em autoatendimento e extrema velocidade operacional.", sinal: "Lojas modulares", abrangencia: "Nacional (Forte no Sul/SP)", dor: "Integração do fluxo de totens digitais com a esteira de montagem sem gargalos na entrega", abordagem: "Layout em linha de produção linear para otimização de tempo e movimento da equipe" },
    { nome: "O Burguês", contato: "oburgues.com", instagram: "@oburgues", tipo: "Delivery e Lojas Físicas", oportunidade: "Forte atuação no modelo de dark kitchen e take away no Rio de Janeiro, expandindo para SP.", sinal: "Dominância regional", abrangencia: "RJ / SP", dor: "Conflito físico entre motoboys esperando pedidos e o fluxo de operação da loja", abordagem: "Desenho de janelas de expedição isoladas e áreas de espera com conforto térmico para entregadores" },
    { nome: "Bucaneiro", contato: "bucaneiroburger.com.br", instagram: "@bucaneiroburger", tipo: "Artesanal", oportunidade: "Crescimento sólido nos bairros do Rio de Janeiro com lojas de perfil rústico e industrial.", sinal: "Abertura de unidades", abrangencia: "RJ", dor: "Adequação de imóveis antigos de rua para suportar carga elétrica e extração de ar", abordagem: "Retrofit de infraestrutura pesada preservando a estética industrial da marca" },
  ],

  "Café": [
    { nome: "Cheirin Bão", tipo: "Cafeteria com café especial sul-mineiro", oportunidade: "Mais de 900 unidades em todos os estados. Maior rede de cafeterias especiais do país.", sinal: "Sempre captando novos pontos", contato: "cheirinbao.com.br", instagram: "@cheirinbao", abrangencia: "Nacional" },
    { nome: "Sterna Café", tipo: "Cafeteria premium de cafés especiais", oportunidade: "Crescimento de 40% em 2024. Meta de 100 unidades, 40 novas em 2025. Lojas instagramáveis.", sinal: "11 contratos assinados início de 2025", contato: "sternacafe.com.br", instagram: "@sternacafe", abrangencia: "Nacional" },
    { nome: "Mr. Black Café", tipo: "Cafeteria gourmet — fundada em BH", oportunidade: "40 unidades, R$ 33 mi faturados em 2025. Expansão para novas praças em 2026.", sinal: "Premiada ABF 4 estrelas — franqueado gestor buscado", contato: "mrblackcafe.com.br", instagram: "", abrangencia: "MG, SP, RJ" },
    { nome: "Grão Espresso", tipo: "Cafeteria — shoppings e centros comerciais", oportunidade: "240+ lojas em 23 estados. Expansão em cidades do interior.", sinal: "Captando franqueados para novas praças", contato: "graoespresso.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Casa Bauducco", tipo: "Cafeteria + empório — quiosque e loja completa", oportunidade: "180+ unidades. Dois formatos: quiosque menor e loja completa.", sinal: "Expansão contínua em shoppings", contato: "casabauducco.com.br", instagram: "@casabauducco", abrangencia: "Nacional" },
    { nome: "The Coffee", contato: "thecoffee.jp", instagram: "@thecoffee.jp", tipo: "To Go / Minimalista", oportunidade: "Lojas ultracompactas (algumas com menos de 10m²). Padrão estético rigoroso.", sinal: "Expansão Nacional", abrangencia: "PR / SP / Nacional", dor: "Encaixar toda a marcenaria, maquinário, hidráulica e estoque em espaços mínimos", abordagem: "Compatibilização milimétrica em BIM para marcenaria técnica e ergonomia em microespaços" },
    { nome: "Mais1 Café", contato: "mais1cafe.com.br", instagram: "@mais1cafe", tipo: "Franquia To Go", oportunidade: "Uma das redes que mais cresce no modelo pegue e leve, ideal para quiosques e pequenas lojas.", sinal: "Centenas de lojas", abrangencia: "Nacional", dor: "Rápida aprovação de projetos padronizados em diferentes prefeituras e shoppings", abordagem: "Elaboração de cadernos executivos padrão e gestão ágil de aprovações legais" },
    { nome: "Go Coffee", contato: "gocoffee.com.br", instagram: "@gocoffeebrasil", tipo: "Cafeteria Grab and Go", oportunidade: "Forte presença em Curitiba e espalhando pelo Sul/Sudeste. Variedade de snacks e bebidas.", sinal: "Expansão orgânica", abrangencia: "PR / SC / SP", dor: "Concorrência de espaço visual entre os equipamentos de café e a vitrine de doces", abordagem: "Desenho de balcões vitrine iluminados que não bloqueiam a interação com o barista" },
    { nome: "Dark Coffee", contato: "darkcoffeebr.com", instagram: "@darkcoffeerio", tipo: "Cafeteria Contemporânea", oportunidade: "Lojas amplas, focadas em coworking e permanência no Centro e Zona Sul carioca.", sinal: "Novas lojas conceito", abrangencia: "RJ", dor: "Gestão acústica em grandes salões com piso duro e muitas pessoas trabalhando", abordagem: "Especificação de forros e revestimentos acústicos disfarçados na decoração estética" },
  ],

  "Restaurante À la Carte": [
    { nome: "Divino Fogão", tipo: "Culinária brasileira — shoppings e dark kitchens", oportunidade: "40 anos de mercado, 173 restaurantes + dark kitchens. Megaloja de 600m² inaugurada em SP em 2025.", sinal: "Novo conceito de megaloja prevê mais unidades", contato: "divinofogao.com.br", instagram: "@divinofogao", abrangencia: "Nacional" },
    { nome: "Griletto", tipo: "Grelhados — praças de alimentação", oportunidade: "Expansão voltada para shoppings. Cozinha para grelhados exige ventilação e equipamentos específicos.", sinal: "Captando franqueados para novos shoppings", contato: "griletto.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Mei Mei", tipo: "Culinária asiática — praças de alimentação", oportunidade: "40m² médios, R$ 250 mil/mês faturados. Expansão em SP, RJ e DF.", sinal: "Retorno 30-48 meses — modelo validado", contato: "meiemei.com.br", instagram: "", abrangencia: "SP, RJ, DF" },
    { nome: "Espetto Carioca", tipo: "Espetinhos — restaurante e dark kitchen", oportunidade: "Modelo híbrido: restaurante físico + dark kitchen. Expansão para cidades menores.", sinal: "Dark kitchen valida expansão para novas praças", contato: "espettocarioca.com.br", instagram: "@espettocarioca", abrangencia: "Nacional" },
    { nome: "Lug's", tipo: "Frango no balde e pratos executivos", oportunidade: "160+ unidades vendidas, expansão nacional e Europa. Dois modelos: shopping e restaurante completo.", sinal: "Expansão internacional sinaliza solidez", contato: "lugs.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Madero Steak House", contato: "restaurantemadero.com.br", instagram: "@maderobrasil", tipo: "Casual Dining", oportunidade: "Operações parrudas em shoppings e rodovias. Cozinhas industriais completas.", sinal: "Potência do Sul", abrangencia: "Nacional", dor: "Logística interna complexa (recebimento de congelados da fábrica vs. produção local)", abordagem: "Dimensionamento correto de câmaras frias e setorização suja/limpa rigorosa" },
    { nome: "Tragga", contato: "tragga.com.br", instagram: "@restaurantetragga", tipo: "Carnes Premium", oportunidade: "Carnes na brasa e culinária sofisticada no Rio de Janeiro. Ambientes de alto padrão.", sinal: "Consolidação na Zona Sul", abrangencia: "RJ", dor: "Carga térmica severa da parrilla impactando o rendimento do chef e da equipe", abordagem: "Projeto de ventilação mecânica com insuflamento de ar fresco focado na praça quente" },
    { nome: "Mocotó", contato: "mocoto.com.br", instagram: "@mocotorestaurante", tipo: "Cozinha Sertaneja", oportunidade: "Lojas em shoppings e expansão do conceito a partir da matriz na Zona Norte de SP.", sinal: "Novos modelos", abrangencia: "SP", dor: "Equipamentos de grande litragem (panelões) que danificam o piso e dificultam a limpeza", abordagem: "Especificação de pisos resinados de alta espessura e ralos lineares industriais" },
    { nome: "Paris 6", contato: "paris6.com.br", instagram: "@paris6", tipo: "Bistrô 24h", oportunidade: "Operação que não para. Obras e manutenções precisam ser cirúrgicas.", sinal: "Modelo de franquia Petit", abrangencia: "Nacional (Forte SP)", dor: "Desgaste acelerado de revestimentos e infraestrutura devido à operação ininterrupta", abordagem: "Utilização de materiais de ultra durabilidade e acesso facilitado para manutenção sem quebrar paredes" },
  ],

  "Buffet Self-Service": [
    { nome: "Panéle (Grupo ATNZO)", tipo: "Culinária italiana — self-service customizável", oportunidade: "Investimento de R$ 89 mil, retorno 12-16 meses. Alta rotatividade exige cozinha bem planejada.", sinal: "Modelo enxuto em expansão nacional", contato: "panele.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Churras Express Brasil", tipo: "Espetos — quiosque, loja, container e móvel", oportunidade: "Investimento R$ 60-120 mil, retorno 4-8 meses. Múltiplos formatos = múltiplos projetos.", sinal: "Alta adaptabilidade — forte demanda", contato: "churrasexpress.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Brasileirinho Delivery", tipo: "Culinária brasileira — delivery e self-service", oportunidade: "Cozinha com produção em larga escala exige projeto técnico detalhado.", sinal: "Franqueados em formação, novos pontos buscados", contato: "brasileirinho.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Churrascaria Terra do Fogo", tipo: "Churrascaria — praças de alimentação", oportunidade: "Shoppings com alto fluxo. Cozinha de churrasco exige especificações técnicas rigorosas.", sinal: "Expansão contínua em praças de alimentação", contato: "terradofogo.com.br", instagram: "", abrangencia: "Nacional" },
    { nome: "Mania de Churrasco", contato: "maniadechurrasco.com.br", instagram: "@maniadechurrascoprime", tipo: "Fast Casual / Churrasco", oportunidade: "Presença maciça nas praças de alimentação. Equipamentos pesados à vista do cliente.", sinal: "Líder em shoppings", abrangencia: "SP / RJ / Nacional", dor: "Restrições rigorosíssimas da engenharia de shoppings para coifas de churrasqueiras", abordagem: "Sistemas de lavadores de gases e precipitadores eletrostáticos para liberação de alvará" },
    { nome: "Spoleto", contato: "spoleto.com.br", instagram: "@spoleto_oficial", tipo: "Culinária Italiana Rápida", oportunidade: "Gigante carioca que está passando por retrofit do projeto arquitetônico (Minha Cozinha Italiana).", sinal: "Retrofit de rede", abrangencia: "Nacional", dor: "Otimização da vitrine de ingredientes refrigerada que sofre com o calor da praça de massas", abordagem: "Desenho de ilhas de cocção frontal com barreira térmica invisível para proteger os frios" },
  ]

};

const BASE_LOOKUP = {};
